"""
Database Configuration for {{ cookiecutter.project_name }}

Generated by REROUTE
"""
{% if cookiecutter.database == 'mongodb' %}# MongoDB Configuration
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("REROUTE_DATABASE_URL", "mongodb://localhost:27017/{{ cookiecutter.project_name }}")

client = AsyncIOMotorClient(DATABASE_URL)
db = client.get_default_database()
{% else %}# SQLAlchemy Configuration
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from contextlib import contextmanager
import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("REROUTE_DATABASE_URL")

if not DATABASE_URL:
    raise ValueError("REROUTE_DATABASE_URL environment variable not set! Check your .env file.")

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    pool_size=5,
    max_overflow=10
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


@contextmanager
def get_db():
    """Database session context manager"""
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def init_db():
    """Create all tables"""
    Base.metadata.create_all(bind=engine)
{% endif %}
